--- #YAML:1.0
name:                Imager-QRCode
version:             0.02
abstract:            Generate QR Code with Imager using libqrencode
license:             ~
author:              
    - Yoshiki KURIHARA <kurihara at cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Encode:                        0
    Imager:                        0.55
    Imager::ExtUtils:              0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
